[workspace]
members = [
  "crates/ak620-core",
  "crates/ak620d",
  "crates/ak620-gui",
]
resolver = "2"

[workspace.package]
version = "0.2.3"
edition = "2024"
rust-version = "1.85"
license = "GPL-3.0-only"

[workspace.lints.rust]
unsafe_code = "forbid"
unreachable_pub = "warn"

[workspace.lints.clippy]
all = "warn"
